package centralnabanka;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-26T22:48:27.259+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://centralnabanka", name = "centralnaBankaPort")
@XmlSeeAlso({ObjectFactory.class, xml.globals.ObjectFactory.class, xml.mt102.ObjectFactory.class, xml.mt103.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CentralnaBankaPort {

    @WebResult(name = "boolean", targetNamespace = "http://centralnabanka", partName = "parameters")
    @WebMethod
    public boolean mt103(
        @WebParam(partName = "parameters", name = "MT103", targetNamespace = "http://xml/mt103")
        xml.mt103.MT103 parameters
    );

    @WebResult(name = "boolean", targetNamespace = "http://centralnabanka", partName = "parameters")
    @WebMethod
    public boolean mt102(
        @WebParam(partName = "parameters", name = "MT102", targetNamespace = "http://xml/mt102")
        xml.mt102.MT102 parameters
    );
}
