package centralnabanka;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-20T22:48:17.555+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://centralnabanka", name = "centralnaBankaPort")
@XmlSeeAlso({ObjectFactory.class, xml.globals.ObjectFactory.class, xml.mt102.ObjectFactory.class, xml.mt103.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CentralnaBankaPort {

    @WebResult(name = "boolean", targetNamespace = "http://centralnabanka", partName = "parameters")
    @WebMethod
    public boolean mt103(
        @WebParam(partName = "parameters", name = "mt103Request", targetNamespace = "http://centralnabanka")
        xml.mt103.MT103 parameters
    );

    @WebResult(name = "boolean", targetNamespace = "http://centralnabanka", partName = "parameters")
    @WebMethod
    public boolean mt102(
        @WebParam(partName = "parameters", name = "mt102Request", targetNamespace = "http://centralnabanka")
        xml.mt102.MT102 parameters
    );
}
