
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package banka;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-21T00:00:45.895+02:00
 * Generated source version: 2.6.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "bankaService",
                      portName = "bankaPort",
                      targetNamespace = "http://banka",
                      wsdlLocation = "WEB-INF/wsdl/banka.wsdl",
                      endpointInterface = "banka.BankaPort")
                      
public class BankaPortImpl implements BankaPort {

    private static final Logger LOG = Logger.getLogger(BankaPortImpl.class.getName());

    /* (non-Javadoc)
     * @see banka.BankaPort#zahtevZaIzvod(xml.zahtevzaizvod.TZahtevZaIzvod  parameters )*
     */
    public xml.izvod.TIzvod zahtevZaIzvod(xml.zahtevzaizvod.TZahtevZaIzvod parameters) { 
        LOG.info("Executing operation zahtevZaIzvod");
        System.out.println(parameters);
        try {
            xml.izvod.TIzvod _return = new xml.izvod.TIzvod();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see banka.BankaPort#mt103(xml.mt103.TMT103  parameters )*
     */
    public boolean mt103(xml.mt103.TMT103 parameters) { 
        LOG.info("Executing operation mt103");
        System.out.println(parameters);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see banka.BankaPort#mt900(xml.mt900.TMT900  parameters )*
     */
    public boolean mt900(xml.mt900.TMT900 parameters) { 
        LOG.info("Executing operation mt900");
        System.out.println(parameters);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see banka.BankaPort#nalogZaPlacanje(xml.nalogzaplacanje.TNalogZaPlacanje  parameters )*
     */
    public boolean nalogZaPlacanje(xml.nalogzaplacanje.TNalogZaPlacanje parameters) { 
        LOG.info("Executing operation nalogZaPlacanje");
        System.out.println(parameters);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see banka.BankaPort#mt910(xml.mt910.TMT910  parameters )*
     */
    public boolean mt910(xml.mt910.TMT910 parameters) { 
        LOG.info("Executing operation mt910");
        System.out.println(parameters);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see banka.BankaPort#mt102(xml.mt102.TMT102  parameters )*
     */
    public boolean mt102(xml.mt102.TMT102 parameters) { 
        LOG.info("Executing operation mt102");
        System.out.println(parameters);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
