package banka;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-21T00:00:45.915+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://banka", name = "bankaPort")
@XmlSeeAlso({xml.nalogzaplacanje.ObjectFactory.class, xml.zahtevzaizvod.ObjectFactory.class, xml.faktura.ObjectFactory.class, xml.globals.ObjectFactory.class, xml.izvod.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BankaPort {

    @WebResult(name = "zahtevZaIzvodResponse", targetNamespace = "http://banka", partName = "parameters")
    @WebMethod
    public xml.izvod.TIzvod zahtevZaIzvod(
        @WebParam(partName = "parameters", name = "zahtevZaIzvodRequest", targetNamespace = "http://banka")
        xml.zahtevzaizvod.TZahtevZaIzvod parameters
    );

    @WebResult(name = "boolean", targetNamespace = "http://banka", partName = "parameters")
    @WebMethod
    public boolean nalogZaPlacanje(
        @WebParam(partName = "parameters", name = "nalogZaPlacanjeRequest", targetNamespace = "http://banka")
        xml.nalogzaplacanje.TNalogZaPlacanje parameters
    );
}
