package banka;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-21T00:00:45.915+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://banka", name = "bankaPort")
@XmlSeeAlso({xml.mt900.ObjectFactory.class, xml.globals.ObjectFactory.class, xml.mt910.ObjectFactory.class, xml.mt102.ObjectFactory.class, ObjectFactory.class, xml.mt103.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BankaPort {

    @WebResult(name = "boolean", targetNamespace = "http://banka", partName = "parameters")
    @WebMethod
    public boolean mt103(
        @WebParam(partName = "parameters", name = "mt103Request", targetNamespace = "http://banka")
        xml.mt103.MT103 parameters
    );

    @WebResult(name = "boolean", targetNamespace = "http://banka", partName = "parameters")
    @WebMethod
    public boolean mt900(
        @WebParam(partName = "parameters", name = "mt900Request", targetNamespace = "http://banka")
        xml.mt900.TMT900 parameters
    );

    @WebResult(name = "boolean", targetNamespace = "http://banka", partName = "parameters")
    @WebMethod
    public boolean mt910(
        @WebParam(partName = "parameters", name = "mt910Request", targetNamespace = "http://banka")
        xml.mt910.TMT910 parameters
    );

    @WebResult(name = "boolean", targetNamespace = "http://banka", partName = "parameters")
    @WebMethod
    public boolean mt102(
        @WebParam(partName = "parameters", name = "mt102Request", targetNamespace = "http://banka")
        xml.mt102.MT102 parameters
    );
}
