
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package centralnabanka;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-20T22:48:17.495+02:00
 * Generated source version: 2.6.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "centralnaBankaService",
                      portName = "centralnaBankaPort",
                      targetNamespace = "http://centralnabanka",
                      wsdlLocation = "WEB-INF/wsdl/centralna_banka.wsdl",
                      endpointInterface = "centralnabanka.CentralnaBankaPort")
                      
public class CentralnaBankaPortImpl implements CentralnaBankaPort {

    private static final Logger LOG = Logger.getLogger(CentralnaBankaPortImpl.class.getName());

    /* (non-Javadoc)
     * @see centralnabanka.CentralnaBankaPort#mt103(xml.mt103.TMT103  parameters )*
     */
    public boolean mt103(xml.mt103.TMT103 parameters) { 
        LOG.info("Executing operation mt103");
        System.out.println(parameters);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see centralnabanka.CentralnaBankaPort#mt102(xml.mt102.TMT102  parameters )*
     */
    public boolean mt102(xml.mt102.TMT102 parameters) { 
        LOG.info("Executing operation mt102");
        System.out.println(parameters);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
